name: github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Install Zola
      run: ./scripts/ci.sh install

    - name: Build production website
      run: ./scripts/ci.sh build

    - name: Push to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - name: Deploy on netlify
      with:
        netlify_hook: ${{ secrets.GITHUB_TOKEN }}
      run: curl -X POST -d {} $netlify_hook
